name: Run CSV Processing

on:
  workflow_dispatch:

jobs:
  run-long-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/upload-artifact@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Download CSV files 
        run: |
          wget -O private_data/domain_list.csv "https://drive.google.com/uc?export=download&id=1BBdnULPxqV7uUHn1mctfte1aa2bz_2p1"
          wget -O private_data/energize_affinity_ids.csv "https://drive.google.com/uc?export=download&id=1UPXSCWfzXdHlUMsXDaHk52LZbM9i7gsO"
          wget -O private_data/enriched_df_preliminary.csv     "https://drive.google.com/uc?export=download&id=1lDDeTJRUyEb1JUmbnDXblB03PPoarufh"
          wget -O private_data/skipped_indices.csv     "https://drive.google.com/uc?export=download&id=1ReWLpq3T-7_S3UkEojFYfXvk8Wfyf3fy"
          wget -O private_data/companies.csv     "https://drive.google.com/uc?export=download&id=1CilJ0-elWqWrJ99PdiXzl-hRtVu28BO6"

      - name: Run main script
        run: python action.py

      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: enriched-output
          path: output/results.csv
